### ISSUE TITLE
Trapv2PDU

### ISSUE THREAD

**Issue by BrunoESP32** [0neblock/Arduino_SNMP#18]
Hi, Aidan!

I was trying to make the "trap" work in the Trapv2 version, but it is only working in version 1.  I used the "PowerSNMP" and the "MIB Browser" to catch the traps, but only version 1 is identified. I couldn't identify the issue....or maybe I'm doing something wrong...

Thanks in advance.

**Comment by 0neblock** [comment]
Hey, sorry for the delay, this should be fixed by #23
