### ISSUE TITLE
No reply to snmpwalk request to .1

### ISSUE THREAD

**Issue by filippsudanov** [0neblock/Arduino_SNMP#30]
Typically devices respond to 
snmpwalk -v 2c -c public <IP> .1

but the library does not.

**Comment by 0neblock** [comment]
As the other OID, you should be able to implement this callback to the OID yourself. The library doesn't implement any built-ins.

**Comment by ae-zero** [comment]
@0neblock 

> As the other OID, you should be able to implement this callback to the OID yourself. The library doesn't implement any built-ins.

Could you give an example?  When you say "implement this callback", do you mean modifying the .cpp/.h files, or do you mean adding a snmp.add<something>Handler to my .ino file?  I've been fighting with trying to get .1 to respond for the better part of a day, and I'm not sure what I'm missing.

@filippsudanov Did you get it working?

Thanks!
