### ISSUE TITLE
No reply to request to 1.0.8802.1.1.2.1.3.6.0

### ISSUE THREAD

**Issue by filippsudanov** [0neblock/Arduino_SNMP#31]
Other snmp daemons reply
No Such Object available on this agent at this OID
to this request, but the library does not reply. 

The OID is legitimate, it's something related to lldp and at least one monitoring software is requesting it when polling snmp devices.

**Comment by 0neblock** [comment]
Hi there,

This library does not attempt to implement any built-in Object handlers.
The OID may be valid, but you will have to implement a response yourself by using `snmp.addIntegerHandler(".1.0.8802.1.1.2.1.3.6.0", ...)`

Looks like you'll be able to find implementation details here: http://www.mibdepot.com/cgi-bin/getmib3.cgi?win=mib_a&i=1&n=LLDP-MIB&r=cisco&f=LLDP-MIB-V1SMI.my&v=v1&t=def#top
