### ISSUE TITLE
Support 

### ISSUE THREAD

**Issue by carlerickrowan** [0neblock/Arduino_SNMP#8]
Is there a plan when sysdescr and other parameters be supported?

typedef struct RFC1213SystemStruct { // TODO: complete this
    char* sysDescr;
    char* sysObjectID;
    char* sysContact;
} RFC1213_list;

**Comment by 0neblock** [comment]
Hi,

I have this working using another library I wrote, in conjunction with this. I will do some testing and include it shortly.

**Comment by 0neblock** [comment]
If youd like to add to the PR here to achieve this, you can https://github.com/0neblock/Arduino_SNMP/pull/25
